# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDu6hE7scW_XCm6O9-GzcCK1Js-IOAXi

demo_test
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile demo_test.sh
# #!/bin/bash
# echo "🔹 Enqueuing sample jobs..."
# python3 queuectl_final_fixed.py enqueue "echo Hello"
# python3 queuectl_final_fixed.py enqueue "sleep 1 && echo Done"
# python3 queuectl_final_fixed.py enqueue "invalid_command"
# 
# echo
# echo "🔹 Running worker..."
# python3 queuectl_final_fixed.py worker
# 
# echo
# echo "🔹 Checking job status..."
# python3 queuectl_final_fixed.py status
# 
# echo
# echo "🔹 Viewing DLQ..."
# python3 queuectl_final_fixed.py dlq

!bash demo_test.sh